---
version: 0.2

env:
  variables:
    key: "value"

phases:
  install:
    commands:
      - echo now is install...
  pre_build:
    commands:
      - echo now into the pre-build...
  build:
    commands:
      - echo now into the real-build...
  post_build:
    commands:
      - echo Uploading artifact to S3.

artifacts:
  files:
    - $ARTIFACT_FILENAME
